import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class AccountData {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  //For the sake of simplicity, a Todo has only a name.
  final String? avatar;
  final int? averageDailysteps;

  AccountData(
    this.id,
    this.avatar,
    this.averageDailysteps,
  );
}//Todo