import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class ActivityData {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  //For the sake of simplicity, a Todo has only a name.
  final double? calories;
  final String? description;
  final double? distance;
  final double? duration;
  final String? name;

  //Default constructor
  ActivityData(
    this.id,
    this.calories,
    this.description,
    this.distance,
    this.duration,
    this.name,
  );
}//Todo