import 'package:floor/floor.dart';

//this say to floor that this class define an entity
@entity
class Annotation {
  @PrimaryKey(autoGenerate: true)
  final int? id; // this is the primary key and it is autogenerated

  final int min; // minutes of meditation
  final int ml; // ml of water that you have drunk (250 ml = 1 glass)
  final String mood; // mood
  final DateTime dateTime; // date and hour

  //constructor
  Annotation(this.id, this.min, this.ml, this.mood, this.dateTime);
} //Annotation
