import 'package:floor/floor.dart';

//this say to floor that this class define an entity
@entity
class Heart {
  @PrimaryKey(autoGenerate: true)
  final int? id; // this is the primary key and it is autogenerated

  final int?
      minutesheart; //minutes in which the heart rate stay in a certain range

  //constructor
  Heart(this.id, this.minutesheart);
}
