import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class HeartData {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  //For the sake of simplicity, a Todo has only a name.
  final int? minutesOutOfRange;
  final int? minutesFatBurn;
  final int? minutesCardio;
  final int? minutesPeak;

  /*
  final int? minimumOutOfRange;
  final int? minimumFatBurn;
  final int? minimumCardio;
  final int? minimumPeak;

  final double? caloriesCardio;
  final double? caloriesFatBurn;
  final double? caloriesOutOfRange;
  final double? caloriesPeak;

  final int? restingHeartRate; 
  */

  //Default constructor
  HeartData(
    this.id,
    this.minutesOutOfRange,
    this.minutesFatBurn,
    this.minutesCardio,
    this.minutesPeak,
  );
}//Todo