import 'package:floor/floor.dart';

//this say to floor that this class define an entity
@entity
class Sleep {
  @PrimaryKey(autoGenerate: true)
  final int? id; // this is the primary key and it is autogenerated

  final int? sleepduration; //minutes of sleeping

  //constructor
  Sleep(this.id, this.sleepduration);
}
